# Generated by Django 4.2.7 on 2025-07-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_post_content_contentblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='background_image',
        ),
    ]
