# Generated by Django 4.2.7 on 2025-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videocategory_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
