# Generated by Django 4.2.7 on 2025-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subscriber_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to feature this post on the main blog page.'),
        ),
    ]
