# Generated by Django 4.2.7 on 2025-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_category_postcategory_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('heading', 'Heading'), ('image', 'Image')], default='rich_text', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Check to feature this post on the main blog page.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Check to feature this video on the main page.'),
        ),
    ]
